name: TaaC-AI Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r https://raw.githubusercontent.com/yevh/TaaC-AI/main/requirements.txt

    - name: Run TaaC-AI script
      run: python https://github.com/yevh/TaaC-AI/blob/main/TaaC-AI.py
