name: TaaC-AI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r https://raw.githubusercontent.com/yevh/TaaC-AI/main/requirements.txt

    - name: Download template.html
      run: |
        curl -o template.html https://raw.githubusercontent.com/yevh/TaaC-AI/main/template.html

    - name: Download OrderService-example.yaml
      run: |
        curl -o OrderService-example.yaml https://raw.githubusercontent.com/yevh/TaaC-AI/main/OrderService-example.yaml
    
    - name: Download AuthService-example.yaml
      run: |
        curl -o AuthService-example.yaml https://raw.githubusercontent.com/yevh/TaaC-AI/main/AuthService-example.yaml

    - name: Download TaaC-AI script
      run: |
        curl -o TaaC-AI.py https://raw.githubusercontent.com/yevh/TaaC-AI/main/TaaC-AI.py

    - name: Run TaaC-AI script with OrderService-example.yaml
      run: python TaaC-AI.py OrderService-example.yaml
      
    - name: Run TaaC-AI script with AuthService-example.yaml
      run: python TaaC-AI.py AuthService-example.yaml

    - name: Execute TaaC-AI script with GPT-4
      run: python TaaC-AI.py OrderService-example.yaml

    - name: Upload report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ThreatModelingReport
        path: .github/workflows/ThreatModelingReport.html
    
